modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="" 

[[mods]]
modId="pumpkineve" 
version="2.0.0"
displayName="Pumpkin Eve"
authors="moadwajad"
description='''
A fresh biome with its varied plants and bone blocks. Fragrant flowers decorate the land, captivating the eye. New foods which have nutrition and culinary uses is added.
'''

[[dependencies.pumpkineve]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"

[[dependencies.pumpkineve]]
modId="forge"
mandatory=true
versionRange="[47.1.29,)"
ordering="NONE"
side="BOTH"

[[dependencies.pumpkineve]]
modId="terrablender"
mandatory=true
versionRange="[3.0.1,)"
ordering="AFTER"
side="BOTH"